<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
	  <PublishAot>true</PublishAot>
	  <PublishTrimmed>true</PublishTrimmed>
	  <!-- Optional, trims unused code -->
	  <InvariantGlobalization>true</InvariantGlobalization>
	  <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
	  <ApplicationIcon>bktico-hi.ico</ApplicationIcon>
	  <Platforms>AnyCPU;x64</Platforms>
	  <!-- Optional, smaller binary -->
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <Optimize>True</Optimize>
    <DebugType>portable</DebugType>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|x64'">
    <Optimize>True</Optimize>
    <DebugType>portable</DebugType>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <DebugType>portable</DebugType>
    <Optimize>True</Optimize>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|x64'">
    <DebugType>portable</DebugType>
    <Optimize>True</Optimize>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="modem.mp3" />
    <None Remove="rsrc\sttw.txt" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="bktico-hi.ico" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="rsrc\eula.txt" />
    <EmbeddedResource Include="rsrc\screenshot16.png" />
    <EmbeddedResource Include="rsrc\sttw.txt" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="NAudio" Version="2.2.1" />
    <PackageReference Include="NLua" Version="1.7.8" />
    <PackageReference Include="Spectre.Console" Version="0.54.1-alpha.0.7" />
    <PackageReference Include="System.Windows.Extensions" Version="10.0.0-rc.2.25502.107" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\aperture\aperture.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Service Include="{508349b6-6b84-4df5-91f0-309beebad82d}" />
  </ItemGroup>

  <ItemGroup>
    <None Update="assets\modem.wav">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="assets\rd_canyon.wav">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="assets\splashes.txt">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>
