<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="rsrc\modem.wav" />
    <EmbeddedResource Include="rsrc\rd_canyon.wav" />
    <EmbeddedResource Include="rsrc\splashes.txt" />
    <EmbeddedResource Include="SECRETS\eula.txt" />
    <EmbeddedResource Include="SECRETS\screenshot16.png" />
    <EmbeddedResource Include="SECRETS\thisisabucket.7z" />
  </ItemGroup>

</Project>
